server:
  port: 8888
  servlet:
    context-path: /config-service

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ecartify/ecartify-config.git
          clone-on-start: false
          basedir: ${CONFIG_SERVER_GIT_REPO_LOCAL_FOLDER:./config/src/main/resources/shared}
  security:
    #hard coding for now
    user:
      name: root
      password: s3cr3t
